# 03 - Layer B: Multi-Echelon Risk Pooling

Quantifies how much safety stock is saved by pooling demand across stores instead of each store holding its own buffer independently. Uses the *real* store-to-store demand correlation, computed from raw `train.csv` (not from the marginal mean/std in `model_inputs.csv`).

In [1]:
import sys
sys.path.append('..')
import pandas as pd
from src.layer_b_pooling import (
    compute_correlation_matrix, decentralized_safety_stock,
    pooled_safety_stock, compare_scenarios, run_all_items,
)

## Formula

**Decentralized:** $SS = z\sqrt{L}\sum_i \sigma_i$

**Pooled:** $SS = z\sqrt{L}\sqrt{\sum_i \sigma_i^2 + \sum_{i \ne j} \rho_{ij}\sigma_i\sigma_j}$

Pooled $\le$ Decentralized whenever $\rho_{ij} < 1$ — this is the risk-pooling effect, quantified rather than asserted.

## Inspect correlation structure for one item first

In [2]:
corr = compute_correlation_matrix(item_id=1)
corr.round(2)

2026-08-28 22:03:42 | INFO     | src.layer_b_pooling | Item 1: correlation matrix computed across 10 stores

store    1     2     3     4     5     6     7     8     9     10
store
1      1.00  0.60  0.59  0.58  0.53  0.54  0.51  0.58  0.59  0.58
2      0.60  1.00  0.61  0.62  0.56  0.55  0.56  0.62  0.63  0.63
3      0.59  0.61  1.00  0.58  0.56  0.54  0.54  0.62  0.61  0.60
4      0.58  0.62  0.58  1.00  0.53  0.54  0.52  0.60  0.60  0.60
5      0.53  0.56  0.56  0.53  1.00  0.49  0.48  0.52  0.54  0.54
6      0.54  0.55  0.54  0.54  0.49  1.00  0.46  0.53  0.54  0.55
7      0.51  0.56  0.54  0.52  0.48  0.46  1.00  0.52  0.54  0.54
8      0.58  0.62  0.62  0.60  0.52  0.53  0.52  1.00  0.62  0.60
9      0.59  0.63  0.61  0.60  0.54  0.54  0.54  0.62  1.00  0.61
10     0.58  0.63  0.60  0.60  0.54  0.55  0.54  0.60  0.61  1.00

In [3]:
import matplotlib.pyplot as plt

plt.figure(figsize=(6, 5))
plt.imshow(corr, cmap='coolwarm', vmin=-1, vmax=1)
plt.colorbar(label='Correlation')
plt.title('Store-to-store demand correlation, Item 1')
plt.xlabel('Store'); plt.ylabel('Store')
plt.show()

C:\Users\Huy\AppData\Local\Temp\ipykernel_19732\1404490168.py:8: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## Compare scenarios for one item

In [4]:
model_inputs = pd.read_csv('../data/processed/model_inputs.csv')
compare_scenarios(item_id=1, model_inputs=model_inputs)

2026-08-28 22:03:44 | INFO     | src.layer_b_pooling | Item 1: correlation matrix computed across 10 stores

2026-08-28 22:03:44 | INFO     | src.layer_b_pooling | Item 1 pooling: decentralized=331.8 pooled=260.8 savings=21.4%

{'item': 1,
 'n_stores': 10,
 'ss_decentralized': np.float64(331.8),
 'ss_pooled': np.float64(260.8),
 'pct_savings': np.float64(21.4),
 'mean_pairwise_correlation': 0.565}

## Run for all 50 items

In [5]:
pooling_results = run_all_items('../data/processed/model_inputs.csv')
pooling_results.sort_values('pct_savings', ascending=False)

2026-08-28 22:03:44 | INFO     | src.layer_b_pooling | Layer B: running risk-pooling comparison for 50 items

2026-08-28 22:03:45 | INFO     | src.layer_b_pooling | Item 1: correlation matrix computed across 10 stores

2026-08-28 22:03:45 | INFO     | src.layer_b_pooling | Item 1 pooling: decentralized=331.8 pooled=260.8 savings=21.4%

2026-08-28 22:03:46 | INFO     | src.layer_b_pooling | Item 2: correlation matrix computed across 10 stores

2026-08-28 22:03:46 | INFO     | src.layer_b_pooling | Item 2 pooling: decentralized=673.4 pooled=601.7 savings=10.6%

2026-08-28 22:03:46 | INFO     | src.layer_b_pooling | Item 3: correlation matrix computed across 10 stores

2026-08-28 22:03:46 | INFO     | src.layer_b_pooling | Item 3 pooling: decentralized=460.5 pooled=389.6 savings=15.4%

2026-08-28 22:03:47 | INFO     | src.layer_b_pooling | Item 4: correlation matrix computed across 10 stores

2026-08-28 22:03:47 | INFO     | src.layer_b_pooling | Item 4 pooling: decentralized=293.9 pooled=230.4 savings=21.6%

2026-08-28 22:03:48 | INFO     | src.layer_b_pooling | Item 5: correlation matrix computed across 10 stores

2026-08-28 22:03:48 | INFO     | src.layer_b_pooling | Item 5 pooling: decentralized=224.9 pooled=171.0 savings=24.0%

2026-08-28 22:03:49 | INFO     | src.layer_b_pooling | Item 6: correlation matrix computed across 10 stores

2026-08-28 22:03:49 | INFO     | src.layer_b_pooling | Item 6 pooling: decentralized=704.7 pooled=632.0 savings=10.3%

2026-08-28 22:03:50 | INFO     | src.layer_b_pooling | Item 7: correlation matrix computed across 10 stores

2026-08-28 22:03:50 | INFO     | src.layer_b_pooling | Item 7 pooling: decentralized=708.3 pooled=633.9 savings=10.5%

2026-08-28 22:03:50 | INFO     | src.layer_b_pooling | Item 8: correlation matrix computed across 10 stores

2026-08-28 22:03:50 | INFO     | src.layer_b_pooling | Item 8 pooling: decentralized=918.8 pooled=842.7 savings=8.3%

2026-08-28 22:03:51 | INFO     | src.layer_b_pooling | Item 9: correlation matrix computed across 10 stores

2026-08-28 22:03:51 | INFO     | src.layer_b_pooling | Item 9 pooling: decentralized=603.6 pooled=532.8 savings=11.7%

2026-08-28 22:03:52 | INFO     | src.layer_b_pooling | Item 10: correlation matrix computed across 10 stores

2026-08-28 22:03:52 | INFO     | src.layer_b_pooling | Item 10 pooling: decentralized=776.8 pooled=709.4 savings=8.7%

2026-08-28 22:03:53 | INFO     | src.layer_b_pooling | Item 11: correlation matrix computed across 10 stores

2026-08-28 22:03:53 | INFO     | src.layer_b_pooling | Item 11 pooling: decentralized=811.2 pooled=738.9 savings=8.9%

2026-08-28 22:03:54 | INFO     | src.layer_b_pooling | Item 12: correlation matrix computed across 10 stores

2026-08-28 22:03:54 | INFO     | src.layer_b_pooling | Item 12 pooling: decentralized=786.2 pooled=714.1 savings=9.2%

2026-08-28 22:03:54 | INFO     | src.layer_b_pooling | Item 13: correlation matrix computed across 10 stores

2026-08-28 22:03:54 | INFO     | src.layer_b_pooling | Item 13 pooling: decentralized=892.9 pooled=824.2 savings=7.7%

2026-08-28 22:03:55 | INFO     | src.layer_b_pooling | Item 14: correlation matrix computed across 10 stores

2026-08-28 22:03:55 | INFO     | src.layer_b_pooling | Item 14 pooling: decentralized=738.1 pooled=659.6 savings=10.6%

2026-08-28 22:03:56 | INFO     | src.layer_b_pooling | Item 15: correlation matrix computed across 10 stores

2026-08-28 22:03:56 | INFO     | src.layer_b_pooling | Item 15 pooling: decentralized=944.9 pooled=874.1 savings=7.5%

2026-08-28 22:03:57 | INFO     | src.layer_b_pooling | Item 16: correlation matrix computed across 10 stores

2026-08-28 22:03:57 | INFO     | src.layer_b_pooling | Item 16 pooling: decentralized=332.7 pooled=268.6 savings=19.2%

2026-08-28 22:03:57 | INFO     | src.layer_b_pooling | Item 17: correlation matrix computed across 10 stores

2026-08-28 22:03:57 | INFO     | src.layer_b_pooling | Item 17 pooling: decentralized=432.1 pooled=360.6 savings=16.5%

2026-08-28 22:03:58 | INFO     | src.layer_b_pooling | Item 18: correlation matrix computed across 10 stores

2026-08-28 22:03:58 | INFO     | src.layer_b_pooling | Item 18 pooling: decentralized=1008.8 pooled=931.5 savings=7.7%

2026-08-28 22:03:59 | INFO     | src.layer_b_pooling | Item 19: correlation matrix computed across 10 stores

2026-08-28 22:03:59 | INFO     | src.layer_b_pooling | Item 19 pooling: decentralized=455.9 pooled=391.7 savings=14.1%

2026-08-28 22:04:00 | INFO     | src.layer_b_pooling | Item 20: correlation matrix computed across 10 stores

2026-08-28 22:04:00 | INFO     | src.layer_b_pooling | Item 20 pooling: decentralized=552.1 pooled=483.8 savings=12.4%

2026-08-28 22:04:01 | INFO     | src.layer_b_pooling | Item 21: correlation matrix computed across 10 stores

2026-08-28 22:04:01 | INFO     | src.layer_b_pooling | Item 21 pooling: decentralized=532.6 pooled=458.5 savings=13.9%

2026-08-28 22:04:01 | INFO     | src.layer_b_pooling | Item 22: correlation matrix computed across 10 stores

2026-08-28 22:04:01 | INFO     | src.layer_b_pooling | Item 22 pooling: decentralized=963.2 pooled=885.5 savings=8.1%

2026-08-28 22:04:02 | INFO     | src.layer_b_pooling | Item 23: correlation matrix computed across 10 stores

2026-08-28 22:04:02 | INFO     | src.layer_b_pooling | Item 23 pooling: decentralized=389.5 pooled=319.0 savings=18.1%

2026-08-28 22:04:03 | INFO     | src.layer_b_pooling | Item 24: correlation matrix computed across 10 stores

2026-08-28 22:04:03 | INFO     | src.layer_b_pooling | Item 24 pooling: decentralized=818.4 pooled=740.4 savings=9.5%

2026-08-28 22:04:04 | INFO     | src.layer_b_pooling | Item 25: correlation matrix computed across 10 stores

2026-08-28 22:04:04 | INFO     | src.layer_b_pooling | Item 25 pooling: decentralized=1060.0 pooled=977.7 savings=7.8%

2026-08-28 22:04:05 | INFO     | src.layer_b_pooling | Item 26: correlation matrix computed across 10 stores

2026-08-28 22:04:05 | INFO     | src.layer_b_pooling | Item 26 pooling: decentralized=609.5 pooled=534.6 savings=12.3%

2026-08-28 22:04:05 | INFO     | src.layer_b_pooling | Item 27: correlation matrix computed across 10 stores

2026-08-28 22:04:05 | INFO     | src.layer_b_pooling | Item 27 pooling: decentralized=283.2 pooled=222.4 savings=21.5%

2026-08-28 22:04:06 | INFO     | src.layer_b_pooling | Item 28: correlation matrix computed across 10 stores

2026-08-28 22:04:06 | INFO     | src.layer_b_pooling | Item 28 pooling: decentralized=1019.4 pooled=943.3 savings=7.5%

2026-08-28 22:04:07 | INFO     | src.layer_b_pooling | Item 29: correlation matrix computed across 10 stores

2026-08-28 22:04:07 | INFO     | src.layer_b_pooling | Item 29 pooling: decentralized=887.9 pooled=806.9 savings=9.1%

2026-08-28 22:04:08 | INFO     | src.layer_b_pooling | Item 30: correlation matrix computed across 10 stores

2026-08-28 22:04:08 | INFO     | src.layer_b_pooling | Item 30 pooling: decentralized=512.4 pooled=439.8 savings=14.2%

2026-08-28 22:04:08 | INFO     | src.layer_b_pooling | Item 31: correlation matrix computed across 10 stores

2026-08-28 22:04:08 | INFO     | src.layer_b_pooling | Item 31 pooling: decentralized=749.0 pooled=669.6 savings=10.6%

2026-08-28 22:04:09 | INFO     | src.layer_b_pooling | Item 32: correlation matrix computed across 10 stores

2026-08-28 22:04:09 | INFO     | src.layer_b_pooling | Item 32 pooling: decentralized=533.8 pooled=463.5 savings=13.2%

2026-08-28 22:04:10 | INFO     | src.layer_b_pooling | Item 33: correlation matrix computed across 10 stores

2026-08-28 22:04:10 | INFO     | src.layer_b_pooling | Item 33 pooling: decentralized=815.4 pooled=742.9 savings=8.9%

2026-08-28 22:04:11 | INFO     | src.layer_b_pooling | Item 34: correlation matrix computed across 10 stores

2026-08-28 22:04:11 | INFO     | src.layer_b_pooling | Item 34 pooling: decentralized=331.8 pooled=267.5 savings=19.4%

2026-08-28 22:04:12 | INFO     | src.layer_b_pooling | Item 35: correlation matrix computed across 10 stores

2026-08-28 22:04:12 | INFO     | src.layer_b_pooling | Item 35 pooling: decentralized=860.7 pooled=780.5 savings=9.3%

2026-08-28 22:04:13 | INFO     | src.layer_b_pooling | Item 36: correlation matrix computed across 10 stores

2026-08-28 22:04:13 | INFO     | src.layer_b_pooling | Item 36 pooling: decentralized=824.3 pooled=755.9 savings=8.3%

2026-08-28 22:04:13 | INFO     | src.layer_b_pooling | Item 37: correlation matrix computed across 10 stores

2026-08-28 22:04:13 | INFO     | src.layer_b_pooling | Item 37 pooling: decentralized=428.6 pooled=352.3 savings=17.8%

2026-08-28 22:04:14 | INFO     | src.layer_b_pooling | Item 38: correlation matrix computed across 10 stores

2026-08-28 22:04:14 | INFO     | src.layer_b_pooling | Item 38 pooling: decentralized=871.9 pooled=802.1 savings=8.0%

2026-08-28 22:04:15 | INFO     | src.layer_b_pooling | Item 39: correlation matrix computed across 10 stores

2026-08-28 22:04:15 | INFO     | src.layer_b_pooling | Item 39 pooling: decentralized=497.1 pooled=430.5 savings=13.4%

2026-08-28 22:04:16 | INFO     | src.layer_b_pooling | Item 40: correlation matrix computed across 10 stores

2026-08-28 22:04:16 | INFO     | src.layer_b_pooling | Item 40 pooling: decentralized=392.1 pooled=322.5 savings=17.7%

2026-08-28 22:04:16 | INFO     | src.layer_b_pooling | Item 41: correlation matrix computed across 10 stores

2026-08-28 22:04:16 | INFO     | src.layer_b_pooling | Item 41 pooling: decentralized=304.8 pooled=238.1 savings=21.9%

2026-08-28 22:04:17 | INFO     | src.layer_b_pooling | Item 42: correlation matrix computed across 10 stores

2026-08-28 22:04:17 | INFO     | src.layer_b_pooling | Item 42 pooling: decentralized=492.0 pooled=416.9 savings=15.3%

2026-08-28 22:04:18 | INFO     | src.layer_b_pooling | Item 43: correlation matrix computed across 10 stores

2026-08-28 22:04:18 | INFO     | src.layer_b_pooling | Item 43 pooling: decentralized=606.7 pooled=535.9 savings=11.7%

2026-08-28 22:04:19 | INFO     | src.layer_b_pooling | Item 44: correlation matrix computed across 10 stores

2026-08-28 22:04:19 | INFO     | src.layer_b_pooling | Item 44 pooling: decentralized=385.3 pooled=317.2 savings=17.7%

2026-08-28 22:04:20 | INFO     | src.layer_b_pooling | Item 45: correlation matrix computed across 10 stores

2026-08-28 22:04:20 | INFO     | src.layer_b_pooling | Item 45 pooling: decentralized=905.3 pooled=833.7 savings=7.9%

2026-08-28 22:04:20 | INFO     | src.layer_b_pooling | Item 46: correlation matrix computed across 10 stores

2026-08-28 22:04:20 | INFO     | src.layer_b_pooling | Item 46 pooling: decentralized=695.1 pooled=622.1 savings=10.5%

2026-08-28 22:04:21 | INFO     | src.layer_b_pooling | Item 47: correlation matrix computed across 10 stores

2026-08-28 22:04:21 | INFO     | src.layer_b_pooling | Item 47 pooling: decentralized=298.9 pooled=234.4 savings=21.6%

2026-08-28 22:04:22 | INFO     | src.layer_b_pooling | Item 48: correlation matrix computed across 10 stores

2026-08-28 22:04:22 | INFO     | src.layer_b_pooling | Item 48 pooling: decentralized=595.3 pooled=526.0 savings=11.6%

2026-08-28 22:04:23 | INFO     | src.layer_b_pooling | Item 49: correlation matrix computed across 10 stores

2026-08-28 22:04:23 | INFO     | src.layer_b_pooling | Item 49 pooling: decentralized=400.7 pooled=330.9 savings=17.4%

2026-08-28 22:04:24 | INFO     | src.layer_b_pooling | Item 50: correlation matrix computed across 10 stores

2026-08-28 22:04:24 | INFO     | src.layer_b_pooling | Item 50 pooling: decentralized=681.0 pooled=616.7 savings=9.4%

2026-08-28 22:04:24 | INFO     | src.layer_b_pooling | Saved Layer B results to C:\Users\Huy\Documents\inventory-optimization-project (1)\data\processed\layer_b_pooling_results.csv

,item,n_stores,ss_decentralized,ss_pooled,pct_savings,mean_pairwise_correlation
4,5,10,224.9,171.0,24.0,0.522
40,41,10,304.8,238.1,21.9,0.558
46,47,10,298.9,234.4,21.6,0.564
3,4,10,293.9,230.4,21.6,0.563
26,27,10,283.2,222.4,21.5,0.566
0,1,10,331.8,260.8,21.4,0.565
33,34,10,331.8,267.5,19.4,0.604
15,16,10,332.7,268.6,19.2,0.605
22,23,10,389.5,319.0,18.1,0.627
36,37,10,428.6,352.3,17.8,0.632
43,44,10,385.3,317.2,17.7,0.634
39,40,10,392.1,322.5,17.7,0.633
48,49,10,400.7,330.9,17.4,0.637
16,17,10,432.1,360.6,16.5,0.655
2,3,10,460.5,389.6,15.4,0.677
41,42,10,492.0,416.9,15.3,0.679
29,30,10,512.4,439.8,14.2,0.699
18,19,10,455.9,391.7,14.1,0.702
20,21,10,532.6,458.5,13.9,0.705
38,39,10,497.1,430.5,13.4,0.715
31,32,10,533.8,463.5,13.2,0.719
19,20,10,552.1,483.8,12.4,0.735
25,26,10,609.5,534.6,12.3,0.735
42,43,10,606.7,535.9,11.7,0.749
8,9,10,603.6,532.8,11.7,0.747
47,48,10,595.3,526.0,11.6,0.748
1,2,10,673.4,601.7,10.6,0.769
13,14,10,738.1,659.6,10.6,0.769
30,31,10,749.0,669.6,10.6,0.771
6,7,10,708.3,633.9,10.5,0.772
45,46,10,695.1,622.1,10.5,0.772
5,6,10,704.7,632.0,10.3,0.775
23,24,10,818.4,740.4,9.5,0.792
49,50,10,681.0,616.7,9.4,0.795
34,35,10,860.7,780.5,9.3,0.797
11,12,10,786.2,714.1,9.2,0.799
28,29,10,887.9,806.9,9.1,0.800
32,33,10,815.4,742.9,8.9,0.805
10,11,10,811.2,738.9,8.9,0.805
9,10,10,776.8,709.4,8.7,0.810
35,36,10,824.3,755.9,8.3,0.818
7,8,10,918.8,842.7,8.3,0.817
21,22,10,963.2,885.5,8.1,0.823
37,38,10,871.9,802.1,8.0,0.823
44,45,10,905.3,833.7,7.9,0.826
24,25,10,1060.0,977.7,7.8,0.829
12,13,10,892.9,824.2,7.7,0.830
17,18,10,1008.8,931.5,7.7,0.831
14,15,10,944.9,874.1,7.5,0.834
27,28,10,1019.4,943.3,7.5,0.835

In [6]:
import matplotlib.pyplot as plt

pooling_results.sort_values('pct_savings').plot(
    x='item', y='pct_savings', kind='bar', figsize=(12, 4), legend=False)
plt.ylabel('% safety stock saved by pooling')
plt.title('Risk pooling savings by item')
plt.tight_layout()
plt.show()

C:\Users\Huy\AppData\Local\Temp\ipykernel_19732\3264849160.py:8: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## Interpretation

Items with lower `mean_pairwise_correlation` should show higher `pct_savings` — check this relationship holds before trusting the numbers further (a positive control on the analysis itself).

In [7]:
import matplotlib.pyplot as plt

plt.scatter(pooling_results['mean_pairwise_correlation'], pooling_results['pct_savings'])
plt.xlabel('Mean pairwise correlation across stores')
plt.ylabel('% safety stock saved by pooling')
plt.title('Sanity check: lower correlation -> higher pooling savings')
plt.show()

C:\Users\Huy\AppData\Local\Temp\ipykernel_19732\1122443704.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()